version: 2

models:
  - name: stg_gl_headers
    description: "Staging model for GL transaction headers"
    columns:
      - name: gl_header_id
        description: "Unique identifier for GL header"
        tests:
          - unique
          - not_null
      - name: transaction_date
        description: "Date when transaction occurred"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= '2020-01-01'"
      - name: fiscal_year
        description: "Fiscal year of transaction"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 2020
              max_value: 2030
      - name: fiscal_period
        description: "Fiscal period (1-12)"
        tests:
          - not_null
          - accepted_values:
              values: [1,2,3,4,5,6,7,8,9,10,11,12]

  - name: stg_gl_lines
    description: "Staging model for GL transaction lines"
    columns:
      - name: gl_line_id
        description: "Unique identifier for GL line"
        tests:
          - unique
          - not_null
      - name: gl_header_id
        description: "Foreign key to GL header"
        tests:
          - not_null
          - relationships:
              to: ref('stg_gl_headers')
              field: gl_header_id
      - name: account_code
        description: "Chart of accounts code"
        tests:
          - not_null
          - relationships:
              to: ref('stg_account_hierarchy')
              field: account_code
      - name: net_amount
        description: "Net amount (debit - credit)"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "!= 0"  # Should not be zero

  - name: stg_account_hierarchy
    description: "Staging model for account hierarchy"
    columns:
      - name: account_code
        description: "Unique account code"
        tests:
          - unique
          - not_null
      - name: account_name
        description: "Account name/description"
        tests:
          - not_null
      - name: account_type
        description: "Account type"
        tests:
          - not_null
          - accepted_values:
              values: ['ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE']
