version: 2

models:
  - name: mart_balance_sheet
    description: "Balance sheet aggregations by account and period"
    tests:
      - test_balance_sheet_balances  # Custom macro to test Assets = Liabilities + Equity
    columns:
      - name: account_code
        description: "Account code from chart of accounts"
        tests:
          - not_null
          - relationships:
              to: ref('dim_accounts')
              field: account_code
      - name: account_type
        description: "Account type - should only be balance sheet accounts"
        tests:
          - not_null
          - accepted_values:
              values: ['ASSET', 'LIABILITY', 'EQUITY']
      - name: period_end_balance
        description: "Account balance at period end"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "!= 0"  # We filter out zero balances

  - name: mart_income_statement
    description: "P&L aggregations by account and period"
    columns:
      - name: account_code
        description: "Account code from chart of accounts"
        tests:
          - not_null
          - relationships:
              to: ref('dim_accounts')
              field: account_code
      - name: account_type
        description: "Account type - should only be P&L accounts"
        tests:
          - not_null
          - accepted_values:
              values: ['REVENUE', 'EXPENSE']
      - name: period_amount
        description: "Account activity for the period"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "!= 0"  # We filter out zero amounts
