version: 2

models:
  - name: dim_accounts
    description: "Account dimension with financial statement categorization"
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('stg_account_hierarchy')
    columns:
      - name: account_code
        description: "Primary key - unique account code"
        tests:
          - unique
          - not_null
      - name: account_name
        description: "Account name"
        tests:
          - not_null
      - name: account_type
        description: "Account type classification"
        tests:
          - not_null
          - accepted_values:
              values: ['ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE']
      - name: statement_type
        description: "Financial statement categorization"
        tests:
          - not_null
          - accepted_values:
              values: ['BALANCE_SHEET', 'INCOME_STATEMENT', 'OTHER']
      - name: balance_multiplier
        description: "Multiplier for balance calculations"
        tests:
          - not_null
          - accepted_values:
              values: [1, -1]

  - name: fct_transactions
    description: "Transaction fact table with account enrichment"
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('stg_gl_lines')
    columns:
      - name: transaction_line_key
        description: "Composite primary key"
        tests:
          - unique
          - not_null
      - name: gl_header_id
        description: "Foreign key to GL header"
        tests:
          - not_null
          - relationships:
              to: ref('stg_gl_headers')
              field: gl_header_id
      - name: gl_line_id
        description: "Foreign key to GL line"
        tests:
          - not_null
          - relationships:
              to: ref('stg_gl_lines')
              field: gl_line_id
      - name: account_code
        description: "Foreign key to account dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_accounts')
              field: account_code
      - name: transaction_date
        description: "Transaction date"
        tests:
          - not_null
      - name: net_amount
        description: "Net transaction amount"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "!= 0"
      - name: signed_amount
        description: "Amount adjusted by balance multiplier"
        tests:
          - not_null
