version: 2

# Existing seeds sources  
sources:
  - name: seeds
    description: "Test data uploaded as seeds"
    
    tables:
      - name: users_test
        description: "Test users data"
      - name: events_test  
        description: "Test events data"

# Raw finance sources for Task 1 migration
  - name: raw_finance
    description: "Raw financial data from legacy systems for Task 1 migration testing"
    database: "{{ env_var('DBT_BIGQUERY_PROJECT_ID') }}"
    schema: raw_finance
    
    tables:
      - name: gl_headers
        description: "General Ledger transaction headers with metadata"
        columns:
          - name: gl_header_id
            description: "Unique identifier for GL header"
            tests:
              - unique
              - not_null
          - name: transaction_number
            description: "Human-readable transaction number"
          - name: transaction_type
            description: "Type of transaction (INVOICE, PAYMENT, SALES, etc.)"
          - name: transaction_source
            description: "Source system (AP, AR, GL)"
          - name: transaction_date
            description: "Date when transaction occurred"
            tests:
              - not_null
          - name: posting_date
            description: "Date when transaction was posted to GL"
          - name: fiscal_year
            description: "Fiscal year of transaction"
            tests:
              - not_null
          - name: fiscal_period
            description: "Fiscal period (1-12)"
            tests:
              - not_null
          - name: currency_code
            description: "Transaction currency (USD, EUR, etc.)"
          - name: status
            description: "Transaction status (POSTED, COMPLETE, etc.)"
          - name: legal_entity_id
            description: "Legal entity identifier"

      - name: gl_lines
        description: "General Ledger transaction lines with account details"
        columns:
          - name: gl_line_id
            description: "Unique identifier for GL line"
            tests:
              - unique
              - not_null
          - name: gl_header_id
            description: "Foreign key to GL header"
            tests:
              - not_null
              - relationships:
                  to: source('raw_finance', 'gl_headers')
                  field: gl_header_id
          - name: account_code
            description: "Chart of accounts code"
            tests:
              - not_null
          - name: entered_dr
            description: "Debit amount in transaction currency"
          - name: entered_cr
            description: "Credit amount in transaction currency"
          - name: accounted_dr
            description: "Debit amount in functional currency"
          - name: accounted_cr
            description: "Credit amount in functional currency"
          - name: cost_center_code
            description: "Cost center for dimensional reporting"
          - name: department_code
            description: "Department for dimensional reporting"
          - name: status
            description: "Line status (POSTED, etc.)"

      - name: account_hierarchy
        description: "Chart of accounts with hierarchy and financial statement mapping"
        columns:
          - name: account_code
            description: "Unique account code"
            tests:
              - unique
              - not_null
          - name: account_name
            description: "Account name/description"
          - name: parent_account_code
            description: "Parent account for hierarchy"
          - name: account_type
            description: "Account type (ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE)"
            tests:
              - not_null
              - accepted_values:
                  values: ['ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE']
          - name: account_level
            description: "Level in account hierarchy (1=top level)"
          - name: normal_balance_side
            description: "Normal balance side (DEBIT or CREDIT)"
            tests:
              - accepted_values:
                  values: ['DEBIT', 'CREDIT']
          - name: is_leaf_account
            description: "Whether this is a detail account (TRUE) or summary (FALSE)"
          - name: financial_statement_line
            description: "Financial statement line item"
          - name: financial_statement_category
            description: "Financial statement category"

 